steps:
  - id: "Clone GitHub"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e

        git config --global http.proxy $(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")
        git config --global https.proxy $(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")
        git clone https://github.com/yamazakikakuyo/test-proxy.git
        mv test-proxy/* .
  
  - id: "Preparation File, Build Docker, Push Docker"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        docker build --no-cache --build-arg SECRET_PROXY="$(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")" -t pipeline_image . -f Dockerfile
        docker tag pipeline_image asia-southeast2-docker.pkg.dev/bdi-onprem/test-proxy-deletable/pipeline-image:latest
        docker push asia-southeast2-docker.pkg.dev/bdi-onprem/test-proxy-deletable/pipeline-image:latest
 
  - id: Download Python Library
    name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e

        root_dir="list_library"
        
        if [ ! -d "$$root_dir" ]; then
            mkdir "$$root_dir"
        fi

        no_proxy="169.254.169.254,metadata,metadata.google.internal,metadata.google.internal."
        export http_proxy=$(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")
        export https_proxy=$(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")
        
        while IFS= read -r library_name || [ -n "$$library_name" ]; do
            [ -z "$$library_name" ] && continue
            pip download "$$library_name" -d "$$root_dir"

        done < list_library.txt

  - id: Upload Python Library
    name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        root_dir="list_library"
        
        no_proxy="169.254.169.254,metadata,metadata.google.internal,metadata.google.internal."
        export http_proxy=$(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")
        export https_proxy=$(gcloud secrets versions access latest --secret="test-proxy" --project="bdi-onprem")
 
        pip install --upgrade twine packaging keyring keyrings.google-artifactregistry-auth

        unset http_proxy 
        unset https_proxy 
        unset no_proxy
        
        for filename in "$$root_dir"/*; do
            python3 -m twine upload \
                --repository-url "https://asia-southeast2-python.pkg.dev/bdi-onprem/python-library-test" \
                --skip-existing \
                "$filename" \
                --verbose
        done

options:
  pool:
    name: 'projects/794055541149/locations/asia-southeast2/workerPools/Test-1'
  logging: CLOUD_LOGGING_ONLY
